### ISSUE TITLE
Show checkboxes in Simple Overview

### ISSUE THREAD

**Issue by Sergiogu2021** [ItCodeNerd/ScarletChainInfoIssues#25]
If you are in Simple Overview the checkboxes "Show reds", "Show plats"... do not update the table.

**Comment by ItCodeNerd** [comment]
Hi, thanks for the feedback, can you check the latest version in production? I cannot seem to reproduce this

**Comment by Sergiogu2021** [comment]
Hello! I can't reproduce it either now. I don't know if it's because of the new 0.4 version or because the problem was on the other computer I was using (same browser though).
