### ISSUE TITLE
Grid blocked at 25/10/2022

### ISSUE THREAD

**Issue by TgCoff** [ItCodeNerd/ScarletChainInfoIssues#27]
Hey my grid is blocked at yesterday i did a rollover and it's not displayed 
![image](https://user-images.githubusercontent.com/17125351/198147136-fbcec3bd-78c8-4ef5-a086-7639e953220f.png)

**Comment by ItCodeNerd** [comment]
Hi, can you mail me your public wallet address so I can have a look at your transactions?

**Comment by TgCoff** [comment]
It's done
